### ISSUE TITLE
Terlan's conversion from ELAN to TEI

### ISSUE THREAD

**Issue by MariaRebecca** [wibarab/corpus-data#5]
Terlan did a conversion yesterday but nothing appears on nosketch

**Comment by simar0at** [comment]
The files habe spaces in their names. See [for example here](https://github.com/wibarab/corpus-data/actions/runs/7100892026/job/19327897797#step:4:1134):   
`/home/runner/work/corpus-data/corpus-data/103_tei_w/2023-12-05_12-44/MOR_Shawiya_Beni Mesnawi_3_interview with grandmother_2022_00_metaMerged.xml`

We do not support spaces. Please rename the files.

**Comment by MariaRebecca** [comment]
thanks
